# Array creation routines

## Ones and zeros

In [2]:
import numpy as np

Create a new array of 2*2 integers, without initializing entries.

In [3]:
np.zeros((2,2), np.int32)

array([[0, 0],
       [0, 0]], dtype=int32)

Let X = np.array([1,2,3], [4,5,6], np.int32). 
Create a new array with the same shape and type as X.

In [4]:
X = np.array([[1,2,3], [4,5,6]], np.int32)

np.array(X)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

Create a 3-D array with ones on the diagonal and zeros elsewhere.

In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a new array of 3*2 float numbers, filled with ones.

In [16]:
np.ones((3,2), dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
x = np.arange(4, dtype=np.int64)
np.ones_like(x)

array([[1, 1, 1, 1]])

Create a new array of 3*2 float numbers, filled with zeros.

In [20]:
np.zeros((3,2), dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.

In [21]:
x = np.arange(4, dtype=np.int64)
np.zeros_like(x)

array([0, 0, 0, 0])

Create a new array of 2*5 uints, filled with 6.

In [23]:
np.full((2,5), 6, dtype= np.uint)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint64)

Let x = np.arange(4, dtype=np.int64). Create an array of 6's with the same shape and type as X.

In [25]:
x = np.arange(4, dtype=np.int64)
np.full_like(x,6)

array([6, 6, 6, 6])

## From existing data

Create an array of [1, 2, 3].

In [27]:
np.array([1,2,3])

array([1, 2, 3])

Let x = [1, 2]. Convert it into an array.

In [28]:
x = [1,2]
np.asarray(x)

array([1, 2])

Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [30]:
X = np.array([[1, 2], [3, 4]])
np.asmatrix(X)

matrix([[1, 2],
        [3, 4]])

Let x = [1, 2]. Conver it into an array of `float`.

In [ ]:
x = [1, 2]
np.asfarr

AttributeError: `np.asfarray` was removed in the NumPy 2.0 release. Use `np.asarray` with a proper dtype instead.

Let x = np.array([30]). Convert it into scalar of its single element, i.e. 30.

In [12]:
x = np.array([30])


Let x = np.array([1, 2, 3]). Create a array copy of x, which has a different id from x.

In [13]:
x = np.array([1, 2, 3])


## Numerical ranges

Create an array of 2, 4, 6, 8, ..., 100.

Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

Create a 1-D array of 50 element spaced evenly on a log scale between 3. and 10., exclusive.

## Building matrices

Let X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11]]).
                 Get the diagonal of X, that is, [0, 5, 10].

In [14]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])


Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.

Create an array which looks like below.
array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

Create an array which looks like below.
array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

Create an array which looks like below. array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])